# Generated by Django 3.1.2 on 2020-10-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fitdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('position', models.BooleanField(default=False)),
                ('gym', models.DateTimeField(default=False)),
                ('exer', models.DateTimeField(default=False)),
                ('yoga', models.DateTimeField(default=False)),
                ('meditation', models.DateTimeField(default=False)),
                ('dance', models.DateTimeField(default=False)),
                ('arbic', models.DateTimeField(default=False)),
            ],
        ),
    ]
