# Generated by Django 3.1.2 on 2020-10-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClubApp', '0003_auto_20201028_0157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
