# Generated by Django 3.1.2 on 2020-10-30 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitnessClubApp', '0006_fitdata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitdata',
            name='arbic',
        ),
        migrations.RemoveField(
            model_name='fitdata',
            name='dance',
        ),
        migrations.RemoveField(
            model_name='fitdata',
            name='exer',
        ),
        migrations.RemoveField(
            model_name='fitdata',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='fitdata',
            name='meditation',
        ),
        migrations.RemoveField(
            model_name='fitdata',
            name='position',
        ),
        migrations.RemoveField(
            model_name='fitdata',
            name='yoga',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
