# Generated by Django 3.1.2 on 2020-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClubApp', '0008_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='arbic',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dance',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gym',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='krate',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yoga',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
    ]
